spring.application.name=portal
spring.datasource.url=jdbc:mysql://localhost:3306/ragbot_db
spring.datasource.username=root
spring.datasource.password=Surya@24
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
rag.service.url=http://localhost:8000/ask
jwt.secret=mySuperSecureSecretKeyForJwtSigning12345
jwt.expiration=86400000
